######################################################################
# Automatically generated by qmake (2.01a) Sat Feb 5 00:55:40 2011
######################################################################

TEMPLATE = app
TARGET = 
DEPENDPATH += .
INCLUDEPATH += .

# Input
HEADERS += main.h photoArchive.h photoArchiveQt.h
SOURCES += main.cc photoArchive.cc photoArchiveQt.cc
