######################################################################
# Automatically generated by qmake (2.01a) Thu Jan 20 16:21:15 2011
######################################################################

TEMPLATE = app
TARGET = 
DEPENDPATH += .
INCLUDEPATH += .

# Input
HEADERS += photoCollectionQt.h
SOURCES += photoCollectionQt.cc
